title: rafikurnia's writing
description: yes, this is a blog!
url: https://rafikurnia.com

author: Rafi Kurnia Putra
social:
  name: Rafi Kurnia Putra
  links:
    - https://id.linkedin.com/in/rafikurnia
    - https://github.com/rafikurnia
    - https://hub.docker.com/u/rafikurnia

google_analytics: UA-134664512-2
google_site_verification: D1ap7HP6ZAAYNqIuNNwbFpAuUitkVfUi0hM2KqTaadU

theme: jekyll-theme-minimal

lang: en-US
logo: /assets/img/logo.png
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/img/logo.png
        height: 320
        width: 320

exclude:
  - assets/scripts/
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-sitemap
