title: rafikurnia's journal
description: A (hopefully) daily updates!
image: /assets/logo.png
author: rafikurnia
lang: en-US
url: https://rafikurnia.com
theme: jekyll-theme-minimal
google_analytics: UA-134664512-2
