title: rafikurnia's journal
description: A (hopefully) daily updates!
image: favicon.ico
author: rafikurnia
lang: en-US
url: rafikurnia.com
theme: jekyll-theme-minimal
google_analytics: UA-134664512-2
