title: rafikurnia's journal
description: A (hopefully) daily update!
url: https://rafikurnia.com

author: Rafi Kurnia Putra
social:
  name: Rafi Kurnia Putra
  links:
    - https://id.linkedin.com/in/rafikurnia
    - https://github.com/rafikurnia
    - https://hub.docker.com/u/rafikurnia

google_analytics: UA-134664512-2
google_site_verification: D1ap7HP6ZAAYNqIuNNwbFpAuUitkVfUi0hM2KqTaadU

theme: jekyll-theme-minimal

lang: en-US
logo: /assets/images/logo.png
defaults:
  - scope:
      path: ""
    values:
      image: 
        path: /assets/images/logo.png
        height: 280
        width: 280
